var Footer=[],
ff="";

Footer.push("<table class=\"TableFooter\">");
Footer.push("	<thead class=\"TheadFooter\">");
Footer.push("		<tr class=\"TrFooter\">");
Footer.push("			<th width=\"4px\">ABOUT ME</th>");
Footer.push("    			<th> </th>");
Footer.push("    			<th>THE REASON WHY</th>");
Footer.push("    			<th> </th>");
Footer.push("    			<th>QUICK LINKS</th>");
Footer.push("			<th> </th>");
Footer.push("    			<th>QUICK INFO</th>");
Footer.push("    			<th> </th>");
Footer.push("    			<th>FOLLOW-ME</th>");
Footer.push("    			<th> </th>");
Footer.push("		</tr>");
Footer.push("	</thead>");
Footer.push("	<tbody class=\"TbodyFooter\">");
Footer.push("		<tr class=\"TrFooter\">");
Footer.push("			<td colspan=\"1\" wrap=\"True\" width=\"50px\" rowspan=\"3\">There are many variations of passages of Lorem Ipsum available. There are many variations of passages of Lorem. There are many variations of passages of Lorem Ipsum available. There are many variations of passages of Lorem.</td>");
Footer.push("			<td> </td>");
Footer.push("			<td>Home</td>");
Footer.push("			<td> </td>");
Footer.push("			<td>Shared Hosting</td>");
Footer.push("    			<td> </td>");
Footer.push("    			<td>Register Domain</td>");
Footer.push("			<td> </td>");
Footer.push("			<td>Facebook</td>");
Footer.push("    			<td> </td>");
Footer.push("		</tr>");
Footer.push("   		<tr class=\"TrFooter\">");
Footer.push("        		<!--<td colspan=\"2\"> </td>-->");
Footer.push("			<td> </td>");
Footer.push("        		<td>About Us</td>");
Footer.push("			<td> </td>");
Footer.push("        		<td>Reseller Hosting</td>");
Footer.push("			<td> </td>");
Footer.push("        		<td>Transfer Domain</td>");
Footer.push("			<td> </td>");
Footer.push("        		<td>Twitter</td>");
Footer.push("			<td> </td>");
Footer.push("    		</tr>");
Footer.push("    		<tr class=\"TrFooter\">");
Footer.push("        		<!--<td colspan=\"2\"> </td>-->");
Footer.push("			<td> </td>");
Footer.push("        		<td>Contact Us</td>");
Footer.push("			<td> </td>");
Footer.push("        		<td>Dedicated Servers</td>");
Footer.push("			<td> </td>");
Footer.push("        		<td>SSL Security</td>");
Footer.push("			<td> </td>");
Footer.push("        		<td>Linkedin</td>");
Footer.push("			<td> </td>");
Footer.push("    		</tr>");
Footer.push("    		<tr class=\"TrFooter\">");
Footer.push("        		<!--<td colspan=\"2\"> </td>-->");
Footer.push("			<td> </td>");
Footer.push("			<td> </td>");
Footer.push("        		<td>Support</td>");
Footer.push("			<td> </td>");
Footer.push("        		<td>VPS Servers</td>");
Footer.push("			<td colspan=\"3\"> </td>");
Footer.push("    			<td>Youtube</td>");
Footer.push("    			<td> </td>");
Footer.push("		</tr>");
Footer.push("    		<tr class=\"TrFooter\">");
Footer.push("        		<td><p>Variations of passages of Lorem variations of passages of Lorem</p></td>");
Footer.push("			<td> </td>");
Footer.push("        		<td>Blog</td>");
Footer.push("			<td> </td>");
Footer.push("        		<td>Wordpress Hosting</td>");
Footer.push("			<td colspan=\"3\"> </td>");
Footer.push("    			<td>Instagram</td>");
Footer.push("    			<td> </td>");
Footer.push("		</tr>");
Footer.push("		<tr class=\"TrFooter\">");
Footer.push("			<!--<td colspan=\"2\"></td>-->");
Footer.push("			<td> </td>");
Footer.push("			<td> </td>");
Footer.push("			<td>Cloud Hosting</td>");
Footer.push("			<td colspan=\"7\"> </td>");
Footer.push("		</tr>");
Footer.push("	</tbody>");
Footer.push("</table>");

function footer(ID){
 for (var i=0;i<Footer.length;i++){
  ff+=Footer[i];
 }
 document.getElementById(ID).innerHTML=ff;
};
//<script type="text/JavaScript" src="http://hanra-projects.unaux.com/side_add_ons/object/footer/footer.js" id="FoOtEr">footer("#FoOtEr")</script>